### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by krylataya** [test-point/testpoint-idp#3]
When you tru to create second user with the same ABN there is a message - "Sorry, this ABN already busy"
I suppose, the correct message should be - "Sorry, this ABN is already busy"

**Comment by krylataya** [comment]
When you create new RP there is a message on top of page - "Username will be equal to ABN; password - any string. ABN must not be taken by someone already."
As far as I understand RP and ABN are not connected so this text should be deleted.

**Comment by krylataya** [comment]
Page https://idp.testpoint.io/users/  - there is "Feel free to choice"
Correct is "Feel free to choose"

**Comment by koriaf** [comment]
All fixed.

**Comment by krylataya** [comment]
Issue is fixed.
