### ISSUE TITLE
upgrade dependencies to avoid securiry flaws

### ISSUE THREAD

**Issue by monkeypants** [test-point/testpoint-idp#6]
GitHub reports `We found a potential security vulnerability in one of your dependencies.`

Unhelpfully, they do not say which one. Please unpin, rebuild, retest each of the requirements.txt one-by (there is only 7) one until they are all at current patch levels, then (assuming the tests pass) repin them.

**Comment by koriaf** [comment]
How do we know that it's fixed? The message goes away?

**Comment by monkeypants** [comment]
I dont understand the warning interface anymore, they broke it. But if everything is pinned at a recent version then (hopefully) it will be more rather than less secure. And maybe github will give us some hint if the vulnerabilities are different.

**Comment by koriaf** [comment]
Did it help?

**Comment by monkeypants** [comment]
The message has gone away :)
